const skills = {
  core: [
    "React.js",
    "Next.js",
    "Express.js",
    "Node.js",
    "TypeScript",
    "Tailwind CSS",
    "Prisma",
    "PostgreSQL",
    "MongoDB",
    "Docker",
    "AWS",
    "Git",
    "Redux Toolkit",
    "Axios",
    "Figma",
  ],
  nonTechnical: [
    "Web Development",
    "Code Review",
    "State Management",
    "Unit Testing",
    "Frontend Development",
    "API Integration",
    "Backend Development",
    "Web Design",
    "Mobile Responsive",
    "Deployment",
    "Integration Testing",
    "UI/UX Design",
    "Version Control",
    "Performance Optimization",
    "Debugging",
    "Database Management",
    "Customer Focus",
    "Team Collaboration",
    "Problem Solving",
    "Communication",
    "Time Management",
    "Critical Thinking",
  ],
  technical: [
    "React.js",
    "Next.js",
    "Express.js",
    "Node.js",
    "TypeScript",
    "Shadcn UI",
    "ANTD",
    "Tailwind CSS",
    "Prisma",
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "Mongoose",
    "Docker",
    "AWS",
    "Vercel",
    "Linux Server",
    "Socket.io",
    "Vitest",
    "Redux Toolkit",
    "Axios",
    "Figma",
    "Docker",
    "Vite",
    "Git",
    "React Query",
    "Github",
    "Google Analytics",
    "SE0",
  ],
};

export default skills;
