// !DEPRECATED: DO NOT USE, USE SKILLS INSTEAD
const techStacks = [
  "React.js",
  "Next.js",
  "Express.js",
  "Node.js",
  "TypeScript",
  "Shadcn UI",
  "ANTD",
  "Tailwind CSS",
  "Prisma",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "Mongoose",
  "Docker",
  "AWS",
  "Vercel",
  "Linux Server",
  "Socket.io",
  "Vitest",
  "Redux Toolkit",
  "Axios",
  "Figma",
  "Docker",
  "Vite",
  "Git",
  "React Query",
  "Github",
  "Google Analytics",
  "SE0",
];

export default techStacks;
